// src/solid/fetch-provider.type.ts
import type { JSX } from 'solid-js'
import type { CreateFetchOptions, FetchClient } from 'tanstack-fetch'
import type { HttpFetchClient } from './fetch-context'

type FetchProviderProps = CreateFetchOptions & {
  children?: JSX.Element
  client?: FetchClient | HttpFetchClient
}

export type { FetchProviderProps }

// src/react/fetch-provider.type.ts
import type { ReactNode } from 'react'
import type { CreateFetchOptions, FetchClient } from 'tanstack-fetch'

type HttpFetchClient = Omit<FetchClient, 'sse'>

type FetchProviderProps = CreateFetchOptions & {
  children: ReactNode
  client?: FetchClient | HttpFetchClient
}

export type { FetchProviderProps, HttpFetchClient }
